// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: feedist/feedist.proto

package types

import (
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	github_com_gogo_protobuf_types "github.com/gogo/protobuf/types"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Feedist struct {
	Index        string                                 `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
	Contract     string                                 `protobuf:"bytes,2,opt,name=contract,proto3" json:"contract,omitempty"`
	Feeshares    github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,3,opt,name=feeshares,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"feeshares"`
	Rewardshares github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,4,opt,name=rewardshares,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"rewardshares"`
	// number of remaining epochs
	Epochs uint32 `protobuf:"varint,5,opt,name=epochs,proto3" json:"epochs,omitempty"`
	// distribution start time
	StartTime time.Time `protobuf:"bytes,6,opt,name=start_time,json=startTime,proto3,stdtime" json:"start_time"`
}

func (m *Feedist) Reset()         { *m = Feedist{} }
func (m *Feedist) String() string { return proto.CompactTextString(m) }
func (*Feedist) ProtoMessage()    {}
func (*Feedist) Descriptor() ([]byte, []int) {
	return fileDescriptor_37dc1a82ccf82720, []int{0}
}
func (m *Feedist) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Feedist) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Feedist.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Feedist) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Feedist.Merge(m, src)
}
func (m *Feedist) XXX_Size() int {
	return m.Size()
}
func (m *Feedist) XXX_DiscardUnknown() {
	xxx_messageInfo_Feedist.DiscardUnknown(m)
}

var xxx_messageInfo_Feedist proto.InternalMessageInfo

func (m *Feedist) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

func (m *Feedist) GetContract() string {
	if m != nil {
		return m.Contract
	}
	return ""
}

func (m *Feedist) GetEpochs() uint32 {
	if m != nil {
		return m.Epochs
	}
	return 0
}

func (m *Feedist) GetStartTime() time.Time {
	if m != nil {
		return m.StartTime
	}
	return time.Time{}
}

func init() {
	proto.RegisterType((*Feedist)(nil), "evmos.v9.feedist.Feedist")
}

func init() { proto.RegisterFile("feedist/feedist.proto", fileDescriptor_37dc1a82ccf82720) }

var fileDescriptor_37dc1a82ccf82720 = []byte{
	// 327 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x51, 0x3d, 0x4f, 0xc3, 0x30,
	0x10, 0x8d, 0x0b, 0x2d, 0xad, 0x01, 0x09, 0x59, 0x05, 0x45, 0x19, 0x92, 0x8a, 0x01, 0x95, 0x01,
	0x5b, 0x82, 0xa9, 0x6b, 0x8b, 0x98, 0x98, 0x22, 0x26, 0x16, 0x94, 0x26, 0xd7, 0x34, 0x82, 0xf4,
	0xa2, 0xd8, 0x2d, 0xe5, 0x5f, 0xf4, 0xf7, 0xf0, 0x0b, 0x3a, 0x76, 0x44, 0x0c, 0x05, 0xb5, 0x7f,
	0x04, 0x25, 0x76, 0xf8, 0x58, 0x59, 0x7c, 0x7e, 0x7e, 0xe7, 0x77, 0x4f, 0xef, 0xe8, 0xf1, 0x08,
	0x20, 0x4a, 0xa4, 0x12, 0xa6, 0xf2, 0x2c, 0x47, 0x85, 0xec, 0x08, 0x66, 0x29, 0x4a, 0x3e, 0xeb,
	0x71, 0xf3, 0xee, 0xb4, 0x63, 0x8c, 0xb1, 0x24, 0x45, 0x71, 0xd3, 0x7d, 0x8e, 0x17, 0x23, 0xc6,
	0x4f, 0x20, 0x4a, 0x34, 0x9c, 0x8e, 0x84, 0x4a, 0x52, 0x90, 0x2a, 0x48, 0x33, 0xdd, 0x70, 0xfa,
	0x5a, 0xa3, 0x7b, 0x37, 0x5a, 0x82, 0xb5, 0x69, 0x3d, 0x99, 0x44, 0x30, 0xb7, 0x49, 0x87, 0x74,
	0x5b, 0xbe, 0x06, 0xcc, 0xa1, 0xcd, 0x10, 0x27, 0x2a, 0x0f, 0x42, 0x65, 0xd7, 0x4a, 0xe2, 0x1b,
	0xb3, 0x5b, 0xda, 0x1a, 0x01, 0xc8, 0x71, 0x90, 0x83, 0xb4, 0x77, 0x0a, 0xb2, 0xcf, 0x97, 0x6b,
	0xcf, 0x7a, 0x5f, 0x7b, 0x67, 0x71, 0xa2, 0xc6, 0xd3, 0x21, 0x0f, 0x31, 0x15, 0x21, 0xca, 0x14,
	0xa5, 0x29, 0x17, 0x32, 0x7a, 0x14, 0xea, 0x25, 0x03, 0xc9, 0xaf, 0x21, 0xf4, 0x7f, 0x04, 0x98,
	0x4f, 0x0f, 0x72, 0x78, 0x0e, 0xf2, 0xc8, 0x08, 0xee, 0xfe, 0x4b, 0xf0, 0x8f, 0x06, 0x3b, 0xa1,
	0x0d, 0xc8, 0x30, 0x1c, 0x4b, 0xbb, 0xde, 0x21, 0xdd, 0x43, 0xdf, 0x20, 0x36, 0xa0, 0x54, 0xaa,
	0x20, 0x57, 0x0f, 0x45, 0x20, 0x76, 0xa3, 0x43, 0xba, 0xfb, 0x97, 0x0e, 0xd7, 0x69, 0xf1, 0x2a,
	0x2d, 0x7e, 0x57, 0xa5, 0xd5, 0x6f, 0x16, 0x2e, 0x16, 0x1f, 0x1e, 0xf1, 0x5b, 0xe5, 0xbf, 0x82,
	0xe9, 0x0f, 0x96, 0x1b, 0x97, 0xac, 0x36, 0x2e, 0xf9, 0xdc, 0xb8, 0x64, 0xb1, 0x75, 0xad, 0xd5,
	0xd6, 0xb5, 0xde, 0xb6, 0xae, 0x75, 0x7f, 0xfe, 0xcb, 0x6c, 0xb9, 0x2a, 0x73, 0xce, 0x7a, 0x62,
	0x5e, 0xad, 0x52, 0x7b, 0x1e, 0x36, 0xca, 0x69, 0x57, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x41,
	0xd8, 0xe2, 0x64, 0xea, 0x01, 0x00, 0x00,
}

func (m *Feedist) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Feedist) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Feedist) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	n1, err1 := github_com_gogo_protobuf_types.StdTimeMarshalTo(m.StartTime, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(m.StartTime):])
	if err1 != nil {
		return 0, err1
	}
	i -= n1
	i = encodeVarintFeedist(dAtA, i, uint64(n1))
	i--
	dAtA[i] = 0x32
	if m.Epochs != 0 {
		i = encodeVarintFeedist(dAtA, i, uint64(m.Epochs))
		i--
		dAtA[i] = 0x28
	}
	{
		size := m.Rewardshares.Size()
		i -= size
		if _, err := m.Rewardshares.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintFeedist(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	{
		size := m.Feeshares.Size()
		i -= size
		if _, err := m.Feeshares.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintFeedist(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if len(m.Contract) > 0 {
		i -= len(m.Contract)
		copy(dAtA[i:], m.Contract)
		i = encodeVarintFeedist(dAtA, i, uint64(len(m.Contract)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Index) > 0 {
		i -= len(m.Index)
		copy(dAtA[i:], m.Index)
		i = encodeVarintFeedist(dAtA, i, uint64(len(m.Index)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintFeedist(dAtA []byte, offset int, v uint64) int {
	offset -= sovFeedist(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Feedist) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Index)
	if l > 0 {
		n += 1 + l + sovFeedist(uint64(l))
	}
	l = len(m.Contract)
	if l > 0 {
		n += 1 + l + sovFeedist(uint64(l))
	}
	l = m.Feeshares.Size()
	n += 1 + l + sovFeedist(uint64(l))
	l = m.Rewardshares.Size()
	n += 1 + l + sovFeedist(uint64(l))
	if m.Epochs != 0 {
		n += 1 + sovFeedist(uint64(m.Epochs))
	}
	l = github_com_gogo_protobuf_types.SizeOfStdTime(m.StartTime)
	n += 1 + l + sovFeedist(uint64(l))
	return n
}

func sovFeedist(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozFeedist(x uint64) (n int) {
	return sovFeedist(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Feedist) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFeedist
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Feedist: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Feedist: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFeedist
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFeedist
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFeedist
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Index = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Contract", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFeedist
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFeedist
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFeedist
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Contract = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Feeshares", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFeedist
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFeedist
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFeedist
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Feeshares.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Rewardshares", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFeedist
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFeedist
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFeedist
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Rewardshares.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Epochs", wireType)
			}
			m.Epochs = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFeedist
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Epochs |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFeedist
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFeedist
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthFeedist
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(&m.StartTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipFeedist(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthFeedist
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipFeedist(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowFeedist
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowFeedist
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowFeedist
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthFeedist
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupFeedist
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthFeedist
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthFeedist        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowFeedist          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupFeedist = fmt.Errorf("proto: unexpected end of group")
)
